package chat

import (
	"bufio"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// grove-315: real-shaped transcripts (lines copied from local orchestrator
// transcripts, prompts scrubbed) — each yields a human label and the right
// entry kinds.
func TestWrapperFixtures(t *testing.T) {
	type ent struct{ Kind, Tool, Text string }
	cases := []struct {
		file    string
		label   string
		entries []ent
	}{
		{
			file:  "caveat-first.jsonl",
			label: "triage the chat-ux backlog",
			entries: []ent{
				{EntryMeta, MetaCommand, "/model"},
				{EntryMeta, MetaLocalStdout, "Set model to `Opus 5.5` and saved as your default for new sessions"},
				{EntryText, "", "triage the chat-ux backlog"},
				{EntryText, "", "On it."},
			},
		},
		{
			file:  "command-only.jsonl",
			label: "/model opus",
			entries: []ent{
				{EntryMeta, MetaCommand, "/model opus"},
				{EntryMeta, MetaLocalStdout, "Set model to `Opus 5.5`"},
			},
		},
		{
			file:  "pasted-content.jsonl",
			label: "ship the release notes for v0.1.40",
			entries: []ent{
				{EntryText, "", "ship the release notes for v0.1.40"},
				{EntryText, "", "and the changelog"},
			},
		},
		{
			file:  "task-notification.jsonl",
			label: "check the e2e suites",
			entries: []ent{
				{EntryText, "", "check the e2e suites"},
				{EntryText, "", "Running them in the background."},
				{EntryMeta, MetaTaskNotification, `Background command "Run e2e suites" completed (exit code 0)`},
			},
		},
		{
			file:  "bash-escape.jsonl",
			label: "why are there 3 windows?",
			entries: []ent{
				{EntryMeta, MetaBash, "tmux ls"},
				{EntryMeta, MetaBashOutput, "grove: 3 windows"},
				{EntryText, "", "why are there 3 windows?"},
			},
		},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			path := filepath.Join("testdata", "wrappers", c.file)
			if got := Label(path, "fallback"); got != c.label {
				t.Errorf("Label = %q, want %q", got, c.label)
			}
			f, err := os.Open(path)
			if err != nil {
				t.Fatal(err)
			}
			defer f.Close()
			p := NewProjector()
			var got []ent
			sc := bufio.NewScanner(f)
			for sc.Scan() {
				for _, e := range p.Line(sc.Bytes()) {
					got = append(got, ent{e.Kind, e.Tool, e.Text})
				}
			}
			if !reflect.DeepEqual(got, c.entries) {
				t.Errorf("entries:\n got %q\nwant %q", got, c.entries)
			}
		})
	}
}

func TestCleanLabel(t *testing.T) {
	cases := map[string]string{
		"plain prompt": "plain prompt",
		"<local-command-caveat>Caveat: The messages below were generated by the user w...": "",
		"<command-name>/clear</command-name>\n <command-message>clear</command-message>":   "/clear",
		"<local-command-stdout>Set model</local-command-stdout>":                           "",
		"<pasted_content id=x>fix the tooltip</pasted_content>":                            "fix the tooltip",
		"<\\pasted_content id=x>fix the tooltip<\\/pasted_content>":                        "fix the tooltip",
		"hello <system-reminder>noise</system-reminder>":                                   "hello",
		"<task-notification>\n<summary>Agent finished</summary>":                           "",
	}
	for in, want := range cases {
		if got := CleanLabel(in); got != want {
			t.Errorf("CleanLabel(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestLabelMissingFileFallsBack(t *testing.T) {
	if got := Label(filepath.Join(t.TempDir(), "nope.jsonl"), "<pasted_content id=1>hi</pasted_content>"); got != "hi" {
		t.Errorf("Label = %q, want hi", got)
	}
}
