package chat

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// grove-315: real-shaped transcripts (lines copied from local orchestrator
// transcripts, prompts scrubbed) — each yields a human label and the right
// entry kinds.
func TestWrapperFixtures(t *testing.T) {
	type ent struct{ Kind, Tool, Text string }
	cases := []struct {
		file    string
		label   string
		entries []ent
	}{
		{
			file:  "caveat-first.jsonl",
			label: "triage the chat-ux backlog",
			entries: []ent{
				{EntryMeta, MetaCommand, "/model"},
				{EntryMeta, MetaLocalStdout, "Set model to `Opus 5.5` and saved as your default for new sessions"},
				{EntryText, "", "triage the chat-ux backlog"},
				{EntryText, "", "On it."},
			},
		},
		{
			file:  "command-only.jsonl",
			label: "/model opus",
			entries: []ent{
				{EntryMeta, MetaCommand, "/model opus"},
				{EntryMeta, MetaLocalStdout, "Set model to `Opus 5.5`"},
			},
		},
		{
			file:  "pasted-content.jsonl",
			label: "ship the release notes for v0.1.40",
			entries: []ent{
				{EntryText, "", "ship the release notes for v0.1.40"},
				{EntryText, "", "and the changelog"},
			},
		},
		{
			file:  "task-notification.jsonl",
			label: "check the e2e suites",
			entries: []ent{
				{EntryText, "", "check the e2e suites"},
				{EntryText, "", "Running them in the background."},
				{EntryMeta, MetaTaskNotification, `Background command "Run e2e suites" completed (exit code 0)`},
			},
		},
		{
			file:  "bash-escape.jsonl",
			label: "why are there 3 windows?",
			entries: []ent{
				{EntryMeta, MetaBash, "tmux ls"},
				{EntryMeta, MetaBashOutput, "grove: 3 windows"},
				{EntryText, "", "why are there 3 windows?"},
			},
		},
		{
			// grove-341: a chat whose only user content is a `!` shell escape
			// still gets a title — the command, not "".
			file:  "bash-only.jsonl",
			label: "$ tmux kill-pane",
			entries: []ent{
				{EntryMeta, MetaBash, "tmux kill-pane"},
				{EntryMeta, MetaBashOutput, "killed pane 3"},
			},
		},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			path := filepath.Join("testdata", "wrappers", c.file)
			if got := Label(path, "fallback"); got != c.label {
				t.Errorf("Label = %q, want %q", got, c.label)
			}
			f, err := os.Open(path)
			if err != nil {
				t.Fatal(err)
			}
			defer f.Close()
			p := NewProjector()
			var got []ent
			sc := bufio.NewScanner(f)
			for sc.Scan() {
				for _, e := range p.Line(sc.Bytes()) {
					got = append(got, ent{e.Kind, e.Tool, e.Text})
				}
			}
			if !reflect.DeepEqual(got, c.entries) {
				t.Errorf("entries:\n got %q\nwant %q", got, c.entries)
			}
		})
	}
}

func TestCleanLabel(t *testing.T) {
	cases := map[string]string{
		"plain prompt": "plain prompt",
		"<local-command-caveat>Caveat: The messages below were generated by the user w...": "",
		"<command-name>/clear</command-name>\n <command-message>clear</command-message>":   "/clear",
		"<local-command-stdout>Set model</local-command-stdout>":                           "",
		"<pasted_content id=x>fix the tooltip</pasted_content>":                            "fix the tooltip",
		"<\\pasted_content id=x>fix the tooltip<\\/pasted_content>":                        "fix the tooltip",
		"hello <system-reminder>noise</system-reminder>":                                   "hello",
		"<task-notification>\n<summary>Agent finished</summary>":                           "",
	}
	for in, want := range cases {
		if got := CleanLabel(in); got != want {
			t.Errorf("CleanLabel(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestLabelMissingFileFallsBack(t *testing.T) {
	if got := Label(filepath.Join(t.TempDir(), "nope.jsonl"), "<pasted_content id=1>hi</pasted_content>"); got != "hi" {
		t.Errorf("Label = %q, want hi", got)
	}
}

// grove-341: precedence — prose, then slash command, then `!` escape — and
// the escape title truncates like any other label.
func TestLabelFallbackPrecedence(t *testing.T) {
	line := func(content string) string {
		b, _ := json.Marshal(content)
		return `{"type":"user","message":{"role":"user","content":` + string(b) + `}}` + "\n"
	}
	t.Run("command beats bash", func(t *testing.T) {
		r := strings.NewReader(line("<bash-input>tmux ls</bash-input>") + line("<command-name>/model</command-name>"))
		if got, ok := labelFrom(r); !ok || got != "/model" {
			t.Errorf("labelFrom = %q, %v; want /model, true", got, ok)
		}
	})
	t.Run("long bash command truncates at 80 runes", func(t *testing.T) {
		long := strings.Repeat("x", 120)
		r := strings.NewReader(line("<bash-input>" + long + "</bash-input>"))
		got, ok := labelFrom(r)
		if !ok || !strings.HasPrefix(got, "$ ") || !strings.HasSuffix(got, "...") || len([]rune(got)) != labelMax {
			t.Errorf("labelFrom = %q, %v; want an 80-rune truncated $-prefixed label", got, ok)
		}
	})
}

// grove-334: Claude Code's interrupt notice is the harness, not the
// operator — every variant is a meta `interrupt` chip, and prose that only
// quotes one stays prose.
func TestClassifyInterrupt(t *testing.T) {
	cases := []struct {
		in, tool, text string
		meta           bool
	}{
		{"[Request interrupted by user]", MetaInterrupt, "Request interrupted by user", true},
		{"[Request interrupted by user for tool use]", MetaInterrupt, "Request interrupted by user for tool use", true},
		{"  [Request interrupted by user for tool use]\n", MetaInterrupt, "Request interrupted by user for tool use", true},
		{"why did you print [Request interrupted by user]?", "", "why did you print [Request interrupted by user]?", false},
		{"[Request interrupted by user]\nnow do X instead", "", "[Request interrupted by user]\nnow do X instead", false},
	}
	for _, c := range cases {
		tool, text, meta := classify(c.in)
		if tool != c.tool || text != c.text || meta != c.meta {
			t.Errorf("classify(%q) = %q, %q, %v; want %q, %q, %v", c.in, tool, text, meta, c.tool, c.text, c.meta)
		}
	}
	if l := CleanLabel("[Request interrupted by user]"); l != "" {
		t.Errorf("an interrupt must never title a chat, got %q", l)
	}
}
